# Generated by Django 6.0.3 on 2026-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_submission_selected_choice_submission_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=-13),
            preserve_default=False,
        ),
    ]
